version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app.DockerFile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  web:
    build:
      context: .
      dockerfile: ./docker/web.DockerFile
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - .:/web
